### ISSUE TITLE
멤버 가입 신청

### ISSUE THREAD

**Issue by AnByoungHyun** [kh-academy-java/kh-academy-java#1]
KH Academy 교육생 분들을 위한 가입 신청 입니다.

댓글로 신청을 하실 때 반드시 다음의 정보를 같이 작성해 주세요.

1. 오전반 또는 오후반 정보
2. 강의장 정보 (H 강의장)
3. 교육생 이름

예시) 오전반 / H 강의장 / 홍길동

위의 정보를 확인 후 멤버로 추가하면 Github 에 가입한 메일로 초대 메일이 보내집니다.

초대 메일을 확인 후 승낙을 하면 비공개 저장소가 보이게 됩니다.

가입 초대 메일을 보낸 후에는 댓글을 삭제할 예정이니 참고하세요.

**Comment by yongjin0217** [comment]
1. 오후반

**Comment by AhnSungHee** [comment]
오후반 / H 강의장 / 안성희

**Comment by ceahl** [comment]
오후반 / H 강의장 / 김창주

**Comment by MDandersonn** [comment]
오후반 /H 강의장 /김영진

**Comment by hscong300** [comment]
1. 오후반
2. H강의장
3. 박현수

**Comment by keep-calm-and-code-on** [comment]
오후반 / H 강의장 / 박지영

**Comment by vceqiv09** [comment]
오후반 / H강의장 / 윤영현

**Comment by Taylor-p-lab** [comment]
오후반 / H 강의장 / 박태현

**Comment by jjongram** [comment]
1. 오후반
2. 2. H 강의장
3. 한종인

**Comment by jmj30040** [comment]
오후반 / H 강의장 / 정명진

**Comment by HyeonJinLeee** [comment]
오후반 / H 강의장 / 이현진

**Comment by Fromredtoviolet** [comment]
오후반 / H 강의장 / 서예인

**Comment by Kim-Min-Hong** [comment]
1. 오후반
2. H강의장
3. 김민홍

**Comment by jeongwoogithub** [comment]
오후반 / H 강의장 / 이정우

**Comment by dduru-nuna** [comment]
1. 오후반
2. H 강의장
3. 서윤지

**Comment by Jinwoo-Ma** [comment]
오후반 / H강의장 / 마진우

**Comment by yrhatesmondays** [comment]
오후반 / H 강의장 / 이유리

**Comment by azure1003** [comment]
오후반 / H강의장 / 황동희

**Comment by namm0915** [comment]
오후반 / H 강의장 / 남채율

**Comment by hoyoukim** [comment]
오후반 / H강의장 / 김호유

**Comment by ParkBmo** [comment]
오후반 / H강의장 / 박현민

**Comment by hvvos** [comment]
오후반 / H 강의장 / 박현우

**Comment by GunhoNam** [comment]
오후반 / H 강의장 / 남건호

**Comment by yuri7860** [comment]
오후반/H강의장/김유리

**Comment by boockgu** [comment]
오후반 / H 강의장 / 김다연

**Comment by Sungyeon99** [comment]
오후반 / H강의장 / 김성연

**Comment by ljwkkkk** [comment]
오후반/ H강의장 / 이진우

**Comment by jihyunkim0** [comment]
오후반/H강의장/김지현

**Comment by NukNim** [comment]
오전반 /H강의실/ 최민건

**Comment by yoonoi** [comment]
오전반 / H 강의장 / 조윤영

**Comment by Taeju2022** [comment]
오전반 / H 강의장 / 장태주

**Comment by seoanchoi** [comment]
오전반 / H 강의장 / 최서안

**Comment by Hsj0511** [comment]
오전반 / H 강의장 / 황수정

**Comment by wjdcks1238** [comment]
오전반 / H 강의장 / 고정찬

**Comment by yoori-kang** [comment]
오전반 / H 강의장 / 강유리

**Comment by sooseong1998** [comment]
오전반 / H강의장 / 진수성

**Comment by silkstring** [comment]
오전반 / H 강의장 / 서채현

**Comment by minseong95** [comment]
오전반 / H 강의장 / 김민성

**Comment by the1989** [comment]
오전반 / H 강의장 / 전경진

**Comment by brown46** [comment]
오전반 / H 강의장 / 김진태

**Comment by kwonnsubin** [comment]
오전반 / H 강의장 / 권수빈

**Comment by KimMilo** [comment]
오전반 / H 강의장 / 김태룡

**Comment by diget611** [comment]
오전반 / H 강의장 / 이상현

**Comment by solarthf** [comment]
오전반 / H 강의장 / 윤솔

**Comment by hyemis** [comment]
오전반 / H 강의장/ 조혜미

**Comment by Hanwxxl** [comment]
오전반 / H 강의장 / 백한울

**Comment by ctrlad** [comment]
오전반/H강의장/이정현

**Comment by SAEBONGCHON** [comment]
오전반 / H 강의장 / 박새롬

**Comment by turtleking33** [comment]
오전반/H강의장/허종인

**Comment by seunggeo** [comment]
오전반 / H 강의장 / 이승걸

**Comment by jaehyunkim123** [comment]
오전반/ H강의장/김재현

**Comment by cheeeeeny** [comment]
오전반 
H강의장
전찬희

**Comment by asfawf** [comment]
오전반 / H 강의장 / 천준혁

**Comment by uzinnn** [comment]
오전반 / H강의장 / 강유진

**Comment by tssoccerz** [comment]
오전반/H강의장/전태석

**Comment by Polygonbugs** [comment]
오전반 / H강의장 / 권제원

**Comment by kyounghoon96** [comment]
오전반/H강의장/오경훈

**Comment by practise30** [comment]
오전반/H강의장/박아연

**Comment by jammy21** [comment]
오후반 / H 강의장 / 최재민

**Comment by Taeju2022** [comment]
오전반 / H 강의장 / 장태주
